### ISSUE TITLE
Update analytics support.

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/bedrock-angular#18]
The current Google Analytics support will only fire an event for the first page loaded.  It does not have support for the current "single page app" style.  Some options:

- Use a GA or general analytics lib:
  - https://angulartics.github.io/
- Update snippet and add SPA support by hand.
  - Example: https://spin.atomicobject.com/2016/11/21/google-analytics-angularjs-app-ngroutes/
  - Ref: https://developers.google.com/analytics/devguides/collection/analyticsjs/
  - Ref: https://developers.google.com/analytics/devguides/collection/analyticsjs/tracking-snippet-reference
- Drop support here and add to new module (which would probably just load https://angulartics.github.io/).
- Drop support here and leave it to applications.

**Comment by dlongley** [comment]
We should probably move support to `bedrock-angular-analytics` and implement the single page stuff.

**Comment by davidlehn** [comment]
Another option:
https://github.com/googleanalytics/autotrack
