### ISSUE TITLE
supportDomain is not an available variable

### ISSUE THREAD

**Issue by lamara** [digitalbazaar/bedrock-angular#7]
On the 404 page, we have a "contact us" help link, like so:

```
<a href="mailto:support@{{supportDomain}}">Customer Support</a>.</p>
```

where supportDomain was probably at one point pulled from a vars config somewhere. This no longer happens though, and supportDomain is not a part of the controller on the component, so it's broken everywhere.

**Comment by davidlehn** [comment]
Fixed issue to avoid markdown trying to render the example HTML.
