### ISSUE TITLE
Use of $onInit and $onChanges

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-angular#9]
I want to have a conversation about our use of these lifecycle hooks.

There is a pattern emerging in a number of modules where we use BOTH the `$onChanges` and `$onInit` hooks to run an `init` function.  Here's an example in bedrock-angular-key:  https://github.com/digitalbazaar/bedrock-angular-key/blob/master/keys-component.js#L40-L48

The first thing I want to make sure we are all aware of is that `$onChanges` is triggered before `$onInit`.  This seems a bit counter-intuitive but according to this issue, it's done this way by design: https://github.com/angular/angular.js/issues/14433

What we see happening in bedrock-angular-key is that `init()` is being called twice for no good reason.  First by `$onChanges`, then again by `$onInit`.  This of course results in redundant HTTP requests etc.

It seems to me that this emerging pattern of calling `init()` in both handlers needs to be revised.

I think that in the case of bedrock-angular-key we could just eliminate the `$onInit` trigger.

**Comment by dlongley** [comment]
> I think that in the case of bedrock-angular-key we could just eliminate the $onInit trigger.

Are we assured that `$onChanges` is always called? If so, it's fine to remove `$onInit`, even if that seems pretty weird.

**Comment by mattcollier** [comment]
Relevant: 
- http://blog.kwintenp.com/the-onchanges-lifecycle-hook/
- http://www.codelord.net/2016/04/14/angular-1-dot-5-new-component-lifecycle-hooks/
-  Translated blog posting indicating that the behavior of $onChanges has been altered from 1.5.3 to 1.5.5
- https://translate.google.com/translate?hl=en&sl=de&tl=en&u=https%3A%2F%2Fjsperts.de%2Fblog%2Fangularjs_life_cycle_hooks_teil_4_onchanges%2F

**Comment by mattcollier** [comment]
Component docs: https://docs.angularjs.org/guide/component

The above German blog post indicated that there is a `isFirstChange()` function that is part of the changes object.

So, I propose we keep the `$onInit` and implement the `$onChanges` handlers like this:

```
  self.$onChanges = function(changes) {
    if(changes.identity && !changes.identity.isFirstChange()) {
      init(changes.identity.currentValue);
    }
  };
```

this works in Angular 1.5.7 (only tested version)
